### ISSUE TITLE
Arabic Commands 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#223]
The tabs at the right of the course are missing in Arabic for Assessments and Resources 
![image](https://user-images.githubusercontent.com/37042927/49155515-cf2c6c00-f323-11e8-95b6-f11fc2909f6b.png)

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Please check and fix

**Comment by HeshamHassan** [comment]
Any update?

**Comment by mohamedMahdyCc** [comment]
@ahmedelbougha @HeshamHassan Done! please confirm and close

**Comment by LamiaSalah** [comment]
@ahmedelbougha  @mohamedMahdyCc  the page format is still messy, no image, large spaces, Courses Assessments still in English

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! we made many lot of updates with this issue, please check and let me know if some thing still messy or confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc Yes it's been taking too long, yet there are still some issues with it! the order of the text in Arabic needs to be changed as I highlighted earlier.
1 الأيام   needs to be switched

also, the spaces and titles need some editing as attached 

![image](https://user-images.githubusercontent.com/37042927/50384540-af902580-06ce-11e9-882f-4a048037137d.png)

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha 
please check it now and let me know if there are some thing messy here

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc the spacing issue still exist 
on the first bar عن هذة الدورة  the rotating button is on the text

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc please change Course Assessments to قياس المهارات in all Arabic courses

**Comment by mohamedMahdyCc** [comment]
> @mohamedMahdyCc the spacing issue still exist
> on the first bar عن هذة الدورة the rotating button is on the text

@LamiaSalah Done

**Comment by mohamedMahdyCc** [comment]
> please change Course Assessments to قياس المهارات in all Arabic courses

working on this

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc please remove the rotating icon on the right tab, keep it as the English version.

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Kindly update.

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  Done
